### ISSUE TITLE
Npm module

### ISSUE THREAD

**Issue by spassvogel** [pixijs/tilemap#81]
Hi, great work on this plugin. I do have a question, or a request rather. These days most people don't import javascript via <script> tags anymore, instead it turns out it's much more convenient to import npm packages. I was wondering if we could import `pixi-tilemap` in a similar manner. Thanks!

**Comment by ivanpopelyshev** [comment]
> These days most people don't import javascript via <script> tags anymore, instead it turns out it's much more convenient to import npm packages

Its not convinient for libraries and plugins developers. We cant just drop vanilla js, and generating module output at the same time with typescvript definition is very hard task and no one solved it so far. 

Many features are missing in typecsript modules, like I just cant merge extra field in class in pixi.

We are making progress with it in main pixi repo. and this year we'll convert all plugins to modules and make big tutorial on how to make your own pixi bundle - that'll help people who still use vanilla to migrate to new world of es6 modules.

Its but people who use those modules do not know of how hard is actually to support it from dev side. `rm -rf node_modules , rm package.lock , npm i` is often solution to many problems.

Here's what you have to do before we actually make all that convertion:

```js
import * as PIXI from 'pixi.js';
window.PIXI = PIXI;
import 'pixi-tilemap';
```

I repeat, again : es6 modules are awesome in theory but spawn many problems for devs and take away so many time, for example me writing this thing. again. because i forgot to put copy of those lines in all pixijs plugins.

**Comment by ivanpopelyshev** [comment]
Yes, it will be solved in the end, but right now it takes our whole team to figure out how to satisfy everyone :)

**Comment by spassvogel** [comment]
Hi Ivan thanks for your response. Great the team is working on it in the main pixi repo.
In the mean time I will use your workaround.

**Comment by eranimo** [comment]
That workaround doesn't work with typescript

**Comment by ivanpopelyshev** [comment]
It works for me in typecript. 

```js
import * as PIXI from 'pixi.js';
window.PIXI = PIXI;
require('pixi-tilemap');
```

typings are also global, you have to use `PIXI.tilemap`

**Comment by Friksel** [comment]
> > These days most people don't import javascript via <script> tags anymore, instead it turns out it's much more convenient to import npm packages
> 
> Its not convinient for libraries and plugins developers. We cant just drop vanilla js, and generating module output at the same time with typescvript definition is very hard task and no one solved it so far.

I don't get this. Since around 2016/2017 I'm using npm and webpack and all modules I'm using fully support ES6 modules for use with npm/Babel/webpack. Except for threejs and pixijs.

For some reason both pixijs as well as threejs seem to think that there are a lot of people still using vanilla js without any bundler, npm, modules. I really don't get that. To me this is like developing for IE8 in 2020, 2021 in 1,5 weeks, looking 6 years into the past.

Right now using pixi plugins feels messy, as it messes up the whole idea of modulair working / optimization by treeshaking in webpack (automatically only including what you use) / not poluting the global space (window object). Resulting in too many bytes in transpiled output code (stuff we don't use, but happen to be in the library, that can't be shaken out by webpack for example). It feels very inefficient and old fashioned.

Could you please explain why threejs and pixijs are so behind on build systems/modulair systems in relation to all other modules out there for the last 4/5 years and seem to limit themselves by thinking there is still a market of people using plain js files with script tags and no bundlers (so important that it limits the mayority of professional developers out there)? I honestly don't get it and try to understand it as it feels to me like it's a result of being scared for new technologies (no offense, just how it looks like to me, I may be completely wrong), but I can't understand that as you are such clever people and create such beautiful stuff, so I'm sure I'm missing something here.

I really would like to understand this. What's holding pixi and threejs back? Sorry for this long post. Thanks in advance!

**Comment by ivanpopelyshev** [comment]
I'm happy to elaborate, because its real pain for me for several years.

1. WebPack + TS = nightmare for plugins. There was no generation of typings of submodules, there was no way to make proper mixins for plugins.
2. Submodules, subpackages - its pain, it was developed years after ES6 imports became a thing. Eben babel moved to `@babel` stuff only in v7 or so.

Like, if you already have class DisplayObject in 'pixi.js' package - you cant alter its typings from outside, and that's basics of modding!

As for advantages, for WebGL apps assets are much, much bigger than source code. Treeshaking is a small problem compared to optimization of said assets.

So its not like "we dont want to go that way", its just big chunk of ecosystem was missing and we didnt want to lose our  other advantages.

I'm very happy that right now all things are coming together and we can finally solve that problem and republish all plugins.

**Comment by ivanpopelyshev** [comment]
There's also a cost of developing it in a team and checking every idea with everyone. PixiJS has much more difficult review process than ThreeJS or Phaser. I still have nightmares about Phaser3 math lib - every function in separate file :)

**Comment by ivanpopelyshev** [comment]
Btw, biggest tool on 2d web is spine, and its runtime uses old-style TS modules because it mirrors what other languges have: https://github.com/EsotericSoftware/spine-runtimes/tree/3.8/spine-ts 

Ask Mario why its like that :)

**Comment by Friksel** [comment]
@ivanpopelyshev Thanks for your quick response Ivan. I don't get everything from your post, but I'm reading a lot about 'types', which are only in Typescript right? ThreeJs also tries to keep everything in Typescript.

Just so I understand the issue: Would the issue still be there when not using/supplying Typescript? So is lies the issue in using Typescript together with the rest of the ecosystem?

And do I get it right that you say that now's the time things come together and start to be possible ecosystem-wise? So it's a matter of time that it will be rewritten to be used without global space (window object) and non-dependent all on the PIXI namespace? Or is that far ahead?

Sorry for all the questions and want to make sure you understand I really do appreciate all your hard work. And also love Pixi as a lib. If we would be able to use both PIXI and the plugins in a modular way with npm and modules (here with webpack) that would be awesome!

Thanks again!

[btw] I understand review processes and developing in a team can be difficult sometimes.

**Comment by ivanpopelyshev** [comment]
Yes, there wouldnt be an issue if we did it without TS, but TS gave us more advantages in maintaining the code than ES6 modules alone would.

As for ecosystem - we now have tools to generate typescript definitions for `@pixi` modules, and a way to make mixins through fake global objects that exist only in typescript. One of things we waited for was `import type` feature in TS 3.7

**Comment by Friksel** [comment]
> Yes, there wouldnt be an issue if we did it without TS, but TS gave us more advantages in maintaining the code than ES6 modules alone would.

Guess you're talking about it being typed (so perhaps better intellicense), being able to use stuff like interfaces etc.? That's a nice addition indeed. And something I was missing when once coming from a C#.net developer (developing windows software) to Javascript over 10 years ago.

I switched to Typescript for a while back in 2013 or so, but at that time transpilers were pretty slow and it felt frustrated to constantly needing to update (third party) definition files to javascript libraries at that time. Also I wasn't sure about how future proof it would be and I like it better to be more on the 'native' side and learn the real thing. 

Later ES6 came and that had changed everything for the better; no more "weird" 'this' object, classes instead of functions, es6 modules, a lot better syntax over the years (way more oop like) and a lot better and faster tools (eslint, webpack, babel, etc.).

So I am really glad I took this route back then. It was hard in the beginning to adjust from C#.net's real OOP to function based Javascript, but last years the language is becoming very mature and gets all features I used back than in C# already. And with Webpack, babel and things like core-js I can work ahead of time with the latest features of Javascript, while being transpiled back to older JS under the hood. So the code is fresh and new and when browsers catch up I only have to re-build with the latest node-modules installed and it's adjusted to the current state of browsers again.

Looking at people using Typescript (which also gained popularity last years, probably also because more and more traditional software developers joined the web and the fact that Babel now can transpile Typescript too), I still see some benefits to using Typescript that ES6+ still can't do. The question is how long that will be the case though.

The most important benefit to using Typescript is probably that it's typed. And that's a huge benefit in intellisense and debugging/error catching. But on the other hand it made me a better developer after I couldn't rely anymore on the incredible intellisense C#.net had in Visual Studio at that time and had do work more secure. And with VS Code we have great intellense now too with Javascript (which is using the same intellisense system as Typescript), especially when also running eslint with a strict config.

I also like the fact that Javascript will never dissapear. While the future of Typescript could change a lot when plain Javascript catches up and starts a typed version for instance. Or imagine when Javascript would switch to be real OOP?! What would be the benefit of Typescript left then? Than it would be just a shell around another language for no reason.

But we're far from it. So guess there's no good or bad choice by chosing Javascript or Typescript. Both have pres and cons.
I'm happy with the choice I made though and ES6+ really is catching up at increasingly speeds now. And there are so many users around the world as it's most probably the no1 language used overall nowadays. So there will be a point that it's taking longer for Typescript to catch up with Javascript than visa versa.

> As for ecosystem - we now have tools to generate typescript definitions for `@pixi` modules, and a way to make mixins through fake global objects that exist only in typescript. One of things we waited for was `import type` feature in TS 3.7

Great to hear! Would be fantastic if we would be able to import stuff in Js like we use to in other libs!

Sorry for rumbling and thanks a lot for your quick responses and the clear explanations. This clears things up!

Have a nice day!

**Comment by ivanpopelyshev** [comment]
> While the future of Typescript could change a lot when plain Javascript catches up and starts a typed version for instance.

I fail to see a problem there. If JS will be typed, it'll still need the same things TS has, so moving tools from TS to modernized JS there shouldnt be a problem. I dont count all the super-modern-type-generics stuff invented to make better angular or react apps - really that's overhead :)

Microsoft is invested in it, with VSCode. Google is invested in TS through Angular, e.t.c.

My second choices would be Dart or Kotlin. Also on my work we have our own fork of typescript with more gamedev-related features.

> Sorry for rumbling and thanks a lot for your quick responses and the clear explanations. This clears things up!

Well, now you describe the problem better than me :)

**Comment by Friksel** [comment]
> I fail to see a problem there. If JS will be typed, it'll still need the same things TS has, so moving tools from TS to modernized JS there shouldnt be a problem. I dont count all the super-modern-type-generics stuff invented to make better angular or react apps - really that's overhead :)
> Microsoft is invested in it, with VSCode. Google is invested in TS through Angular, e.t.c.

That's why I wrote: there's no good or bad choice at the moment. Both have pre's and cons really.
I don't see Typescript disapear coming three years for sure. And see a rise in Typescripts popularity. Which probably also has a lot to do with Babel being able to transpile both Javascript and Typescript, so coming from the Javascript side it's the same toolset to use for Typescript which makes a crossover easier.

That said, in the end everything is Javascript anyhow. No matter if coming from a Typescript source or a future Javascript source transpiled back. And both are transpiled to other code. So in the end it really doesn't matter for the end result as both teams have great parties investing in it. I also thought about moving over to Typescript again last year, because of Babel, but decided not to for now. In the end none of the two are real OOP in the first place and things like inheritance are always transpiled back to Javascript and pure javascript just CAN't really inherit like real OOP can. Because it's not oop, but function based to begin with. So it's always a compromise.

There really is no better on one side over the other at this point, just preference and where priorities are I think. 

And I personally think the characteristic of a developer to be able to adopt to systems is way more important. As things change over night anyhow.

Anyway, looks like we're on the same page :). [/offtopic mode off]

**Comment by SukantPal** [comment]
2.1.4 should solve this problem with PixiJS v6.
